version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 933534344279.dkr.ecr.us-east-2.amazonaws.com
      - echo Logging in to Docker Hub...
      - echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin

  build:
    commands:
      - echo Building the JAR with Gradle...
      - chmod +x gradlew
      - ./gradlew build --no-daemon
      - echo Building the Docker image...
      - docker build -t elephantapi .
      - docker tag elephantapi:latest 933534344279.dkr.ecr.us-east-2.amazonaws.com/elephantapi:latest

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 933534344279.dkr.ecr.us-east-2.amazonaws.com/elephantapi:latest
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"elephant-backend","imageUri":"933534344279.dkr.ecr.us-east-2.amazonaws.com/elephantapi:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
