version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "982534361279"
    AWS_DEFAULT_REGION: "us-east-2"
    IMAGE_REPO_NAME: "elephantapi"

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Making Gradle wrapper executable..."
      - chmod +x ./gradlew

  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION \
        | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo "Building JAR with Gradle..."
      - ./gradlew clean build -x test
      - echo "Gradle build succeeded. Building Docker image..."
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:latest \
        $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest

  post_build:
    commands:
      - echo "Pushing Docker image to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest
      - echo "Image pushed successfully to ECR at $(date)"

      - printf '[{"name":"'$IMAGE_REPO_NAME'","imageUri":"'$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:latest'"}]' \
        > imagedefinitions.json
      - echo "Created imagedefinitions.json:"
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
